USE [master]
GO

CREATE DATABASE [apmlabs]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [apmlabs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [apmlabs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [apmlabs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [apmlabs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [apmlabs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [apmlabs] SET ARITHABORT OFF 
GO

ALTER DATABASE [apmlabs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [apmlabs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [apmlabs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [apmlabs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [apmlabs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [apmlabs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [apmlabs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [apmlabs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [apmlabs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [apmlabs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [apmlabs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [apmlabs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [apmlabs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [apmlabs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [apmlabs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [apmlabs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [apmlabs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [apmlabs] SET RECOVERY FULL 
GO

ALTER DATABASE [apmlabs] SET  MULTI_USER 
GO

ALTER DATABASE [apmlabs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [apmlabs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [apmlabs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [apmlabs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [apmlabs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [apmlabs] SET  READ_WRITE 
GO


